# ServiceAccount for Prometheus
# automountServiceAccountToken harus true agar kubernetes_sd_configs bisa akses API

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: monitoring
  labels:
    app.kubernetes.io/name:      prometheus
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: true
